### ISSUE TITLE
IgnoreErrorExtension not ignoring my error

### ISSUE THREAD

**Issue by demmmmios** [contributte/sentry#7]
Hi my config is:

```
sentry:
    enable: %productionMode%
    client:
        dsn: https://xxxxxxxxxxxxxx.cz/1
        integrations:
            - Contributte\Sentry\Integration\IgnoreErrorIntegration([
                ignore_exception_regex: [
                    '/Core Warning/'
                ],
                ignore_message_regex: [
                    '/Core Warning/'
                ],
            ])
```

and I still have this error in sentry

```
[Sentry\Exception\FatalErrorException Unknown in ?]
Core Warning: Module 'ssh2' already loaded
```

This error is like 12K per day and server admins are unable ti fix it. Am i missing something in config or so?

**Comment by f3l1x** [comment]
Hi @demmmmios.

Take a look at some example.

```neon
Contributte\Sentry\Integration\IgnoreErrorIntegration([
	ignore_exception_regex: [
		'/^(PHP )?Deprecated: Function m(de)?crypt(_[a-z]+)+\(\) is deprecated.*$/',
		'/^(PHP )?Deprecated: Function openssl(_[a-z]+)+\(\) is deprecated.*$/'
	],
	ignore_message_regex: [
		'/^(PHP )?Deprecated: Function m(de)?crypt(_[a-z]+)+\(\) is deprecated.*$/',
		'/^(PHP )?Deprecated: Function openssl(_[a-z]+)+\(\) is deprecated.*$/'
	],
])

```

**Comment by demmmmios** [comment]
These two regex must match both? I have realy simple regex `Core Warning` that should match this message `Core Warning: Module 'ssh2' already loaded`

**Comment by f3l1x** [comment]
Perhaps you can setup some MVP in here https://github.com/contributte/sentry-skeleton.

**Comment by Creeperface01** [comment]
@f3l1x isn't `SentryExtension` supposed to just add default integrations instead of replace those added in config?

**Comment by MartinKokesCz** [comment]
@f3l1x Should be closed now.

@demmmmios I know, that it is little bit late, but I have checked your issue, because I had the same.

For example in https://github.com/contributte/sentry-skeleton there are:
1) name of exception - RuntimeException
2) and exception text This is example error. Date is "11.09.2023 1313:0909:2626"

### If you want to ignore this exception you will have to make regex:

```
ignore_exception_regex: [
    '/This is example error\. Date is \"(.*)\"/'
],
```


				
### This will not work:
```
ignore_exception_regex: [
    '/RuntimeException(.*)/'
],
```



Also don't forget to:
1) have correct indentation (tabs/spaces) in neon files if you copy rules from anywhere.
2) check your regex (especially special chars) for example on https://regex101.com/
3) clear cache, after changing anything in neon configuration files.

**and the best in the end :-) - solution for your issue** 
```
ignore_exception_regex: [
    '/Module \'ssh2\' already loaded/'
],
```

**Comment by f3l1x** [comment]
Thanks, closing.
